### ISSUE TITLE
No Kubernetes section

### ISSUE THREAD

**Issue by timogoosen** [ruanbekker/awesome-list#1]
I was trying to find the Kubernetes section here.
Lol Hallo Ruan het bietjie jou wiki uitgecheck toe dink ek dit sal dalk funny wees om 'n issue op jou awesome list te maak.

**Comment by ruanbekker** [comment]
Fixed 😄 
https://github.com/ruanbekker/awesome-list/blob/master/README.md#kubernetes

**Comment by timogoosen** [comment]
Lol awesome!
